### ISSUE TITLE
Confirmation that Chrome Web Store Extension is secure

### ISSUE THREAD

**Issue by Alk2** [deanoemcke/thegreatdiscarder#11]
Hello,

Firstly, I want to thank you for all of the hard work that you have put into developing this extension and The Great Suspender, which I have been using. I am aware of last week's unfortunate compromise of The Great Suspender and I became aware of The Great Discarder through one of your comments. Thank you also for managing last week's issue with diligence, openness and speed. To that end, I notice that The Great Discarder extension on the Chrome Web Store has been updated on June 8th. When I looked at the extension earlier last week, the last update was in December. When I compared the version from the web store with the version in Github, there were some differences (according to Winmerge). Could you please verify that the version on the Chrome Web Store is safe to use?

Thank you very much.

**Comment by deanoemcke** [comment]
Sorry about the late reply on this. Yes, this extension was never compromised. As in, I retained ownership of it throughout the compromise of The Great Suspender.
The recent update was due to me revisiting the extension recently.
