### ISSUE TITLE
Discard all other tabs immediately after pressing on icon

### ISSUE THREAD

**Issue by arturkohut** [deanoemcke/thegreatdiscarder#5]
Add option to the settings for discarding all other tabs (or current tab) after pressing on icon instead of showing popup.

**Comment by deanoemcke** [comment]
I like the concept but I'm not sure it provides the best user experience. I prefer the UI to be as consistent as possible for all users. 
Surely keyboard shortcuts are a better way to achieve this?

**Comment by arturkohut** [comment]
When I restart my Chrome, a lot of tabs which was discarded before, trying to load.
So, I may wait some time (aprx 2 mins) or press discard other tabs in popup menu.
When Chrome is aggressively load all this tabs, pop menu is pretty laggy.
I am not really keyboard user. Because I use a lot of programs, and it's pretty difficult to remember all shortcuts.
It would be a great option to change button behavior.

**Comment by deanoemcke** [comment]
Ah, how about an option to always discard background tabs automatically when the browser is restarted?
That would be even better than having to click the button right?

**Comment by deanoemcke** [comment]
https://github.com/deanoemcke/thegreatdiscarder/issues/2
