### ISSUE TITLE
Automatic discard not working?

### ISSUE THREAD

**Issue by bro3234** [deanoemcke/thegreatdiscarder#7]
I have tabs set to automatically discard after 30 minutes but when I go to a tab that was definitely inactive for over 30 minutes, it wasn't discarded at all.

**Comment by deanoemcke** [comment]
I'll try to look into it. In the meantime, to help debug the issue, you can try visiting `chrome://discards` in your browser to help cross check that the extension is working as intended.

**Comment by bro3234** [comment]
I think I might've been mistaken.  It was after a reboot and after reopening Chrome that all the tabs were active.  Guess I was confused because I'm used to The Great Suspender which keeps tabs suspended even after a reboot and reopen.  Is this the intended behavior for The Great Discarder?

**Comment by deanoemcke** [comment]
No unfortunately. Although I am looking at a potential feature that will discard all tabs immediately on restart.

**Comment by bro3234** [comment]
That would be great.  Thank you.
